# Generated by Django 5.2 on 2025-07-24 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_left', models.IntegerField(help_text='Distance in km', null=True)),
                ('duration_right', models.IntegerField(help_text='Distance in km', null=True)),
                ('child_left', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_connections', to='main.newaiportmodel')),
                ('child_right', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_connections', to='main.newaiportmodel')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='main.newaiportmodel')),
            ],
        ),
    ]
