# Generated by Django 5.2 on 2025-05-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airportroutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Connetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_code', models.CharField(max_length=8, unique=True)),
                ('position', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.airportroutes')),
            ],
        ),
    ]
