# Generated by Django 5.2 on 2025-05-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_connetion_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='connetion',
            name='node',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.airportroutes'),
            preserve_default=False,
        ),
    ]
