# Generated by Django 5.2 on 2025-05-02 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_connetion_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connetion',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airportroutes'),
        ),
    ]
