# Generated by Django 5.2 on 2025-05-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_connetion_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connetion',
            old_name='current_code',
            new_name='destination_code',
        ),
        migrations.RenameField(
            model_name='connetion',
            old_name='node',
            new_name='takeoff_code',
        ),
    ]
