# Generated by Django 5.2 on 2025-05-02 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_current_code_connetion_destination_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connetion',
            name='destination_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_code', to='core.airportroutes'),
        ),
    ]
