# Generated by Django 5.2 on 2025-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_connetion_destination_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportroutes',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
