# Generated by Django 5.2 on 2025-05-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_airportroutes_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Airport IATA code (e.g., JFK, LAX)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Airport name', max_length=100)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='connetion',
            name='takeoff_code',
        ),
        migrations.RemoveField(
            model_name='connetion',
            name='destination_code',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Node position in the route')),
                ('duration', models.IntegerField(help_text='Flight duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='core.airport')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('origin', 'destination', 'position')},
            },
        ),
        migrations.DeleteModel(
            name='Airportroutes',
        ),
        migrations.DeleteModel(
            name='Connetion',
        ),
    ]
