# Generated by Django 4.2.11 on 2025-06-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_airport_remove_connetion_takeoff_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('duration', models.IntegerField(help_text='Distance in km')),
            ],
        ),
        migrations.RemoveField(
            model_name='airport',
            name='city',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='name',
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddField(
            model_name='airportroute',
            name='from_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.airport'),
        ),
        migrations.AddField(
            model_name='airportroute',
            name='to_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.airport'),
        ),
    ]
